server:
  port: 4500
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ # this is the eureka server address
  instance:
    appname: productservice
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordermgmtdb
    username: root
    password: secret
    driverClassName: com.mysql.jdbc.Driver
    maximum-pool-size: 30
  cloud:
    application:
      name: productservice
    
    