spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: pass@word1
    driverClassName: com.mysql.jdbc.Driver
    maximum-pool-size: 30
  application:
      name: productservice
server:
  port: 5000
  